# Generated by Django 3.1.5 on 2021-01-10 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ghar_dikhao', '0005_auto_20210110_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='user',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
