# Generated by Django 3.1.5 on 2021-01-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghar_dikhao', '0007_auto_20210110_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisment',
            name='user',
        ),
    ]
