# Generated by Django 3.1.5 on 2021-01-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghar_dikhao', '0010_usercustom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usercustom',
        ),
    ]
