# Generated by Django 3.1.5 on 2021-01-10 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ghar_dikhao', '0004_auto_20210110_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='description',
            field=models.CharField(default='', editable=False, max_length=700),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='title',
            field=models.CharField(default='', editable=False, max_length=70),
        ),
    ]
