# Generated by Django 3.1.5 on 2021-01-11 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ghar_dikhao', '0014_getkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='getkey',
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
