# Generated by Django 3.1.5 on 2021-01-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghar_dikhao', '0016_auto_20210111_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
