# Generated by Django 3.1.5 on 2021-01-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghar_dikhao', '0018_auto_20210112_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='view_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
