# Generated by Django 3.1.5 on 2021-01-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghar_dikhao', '0021_auto_20210113_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='bedroom',
            field=models.IntegerField(error_messages={'invalid': 'Enter a valid bedroom'}),
        ),
    ]
