# Generated by Django 3.1.5 on 2021-01-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghar_dikhao', '0022_auto_20210113_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='email',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='first_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='last_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='city',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='phone',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='state',
            field=models.TextField(default='', max_length=100),
        ),
    ]
